=== mikebox/breakfast/Training/WelcomeMessage/etc/welcome_message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="welcome_message">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="country" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="default">
                <xs:simpleType>
                  <xs:restriction base="xs:string" />
                </xs:simpleType>
              </xs:element>
              <xs:element name="state" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="code" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="code" use="required" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mikebox/breakfast/Training/WelcomeMessage/etc/welcome_message.xml
<?xml version="1.0"?>
<welcome_message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Training_WelcomeMessage:etc/welcome_message.xsd">
    <country code="IN">
        <default>Welcome to India</default>
        <state code="TN">Welcome to TN</state>
        <state code="KA">Welcome to KA</state>
    </country>
    <country code="US">
        <default>Welcome to US</default>
        <state code="CA">Welcome to CA</state>
    </country>
</welcome_message>
